#! /bin/sh
sn=${BASH_SOURCE[0]}
for pid in $(pidof -x $sn); do
	if [ $pid != $$ ]; then
		kill $pid
	fi
done
killall sxhkd
killall polybar

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7
bspc config normal_border_color \#21618c
bspc config focused_border_color \#1b4f72
bspc config border_width         2
bspc config window_gap          16
bspc config norma
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/Pictures/wallpaper
xinput set-prop 12 280 1
~/.config/polybar/launch.sh
xdo lower -N Polybar
